""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Config Basics
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

function s:basic_config()
    " 侦测文件类型载入对应的语法及缩进
    syntax on
    filetype on
    filetype plugin on
    filetype indent on

    colorscheme default

	set nocompatible
	set number
	set ruler
	set wildmenu
	set wildmode=list:longest

	set hlsearch
	set incsearch
	set noignorecase

    set nowrap
	set linebreak
	set nobackup
	set showmatch

	set smartindent
	set autoindent
	set expandtab	    "replace tab with space
	set smarttab	    "easy when ou use backspace
	set tabstop=4
	set shiftwidth=4
	set numberwidth=4
	set backspace=2

	set fileencoding=utf-8
	set fileencodings=utf-8,bgk
	set fileformat=unix
	set fileformats=unix,dos,mac

    "ctrl + o 标签打开文件
    nmap <C-o> :tabnew 


    "tab和Shift tab要标模式下切换标签
    nmap <Tab> :tabn<CR>
    nmap <S-Tab> :tabp<CR>

endfunction


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Config File
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"config function of c file
function s:filetype_c()
    nmap <K> :!gcc -Wall % -O /tmp/main<CR>
endfunction


"config function of js file
function s:filetype_js()
endfunction


"config function of css file
function s:filetype_css()
endfunction


"config function of php file
function s:filetype_php()
    nmap <K> :!pman $<CR>
    nmap <C-j> :!php -l %<CR>
    nmap <C-p> :!php %<CR>

endfunction


"config function of nginx configure file
function s:filetype_nginx()
endfunction




function s:new_file_c()
endfunction


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Excute Part
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

call s:basic_config()


"
autocmd FileType c call s:filetype_c()
autocmd FileType js call s:filetype_js()
autocmd FileType css call s:filetype_css()
autocmd FileType php call s:filetype_php()
autocmd FileType nginx call s:filetype_nginx()


